[package]
name = "timechain_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
nostr-sdk = "0.37.0"
reqwest = "0.12.11"
serde_json = "1.0.134"
thousands = "0.2.0"
tokio = { version = "1.43.1", features = ["full"] }
tweety-rs = "0.1.4"
